name: CI

on:
  push:
    branches: [ "a4i/main", "a4i/staging", "alex/fe-docker"]
  pull_request:
    branches: [ "a4i/main", "a4i/staging" ]
  workflow_dispatch:

jobs:
  ci-frontend:
    uses: ./.github/workflows/ci-frontend.yaml
    secrets: inherit
    with:
      publish_staging: ${{ github.event_name == 'push' && github.ref_name == 'a4i/staging' }}
      publish_latest: ${{ github.event_name == 'push' && github.ref_name == 'a4i/main' }}
